services:
  mediator:
    build: .
    container_name: mediator
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery:
    build: .
    container_name: celery-worker
    command: celery -A mediator.worker worker --loglevel=info
    env_file: ".env"
    depends_on:
      - db
      - rabbitmq

volumes:
  pgdata:
  rabbitmq_data:
